#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/core/sdk:3.1

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: MSmileDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "1882320"
        ConnectionStrings__MSmileDb: "HOST=127.0.0.1;DB=MSmileDb;UID=postgres;PWD=1882320;PORT=5432;"

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - dotnetcore
            script:
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - cd source
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release
