version: '3'

services:
  pg_db:
    image: postgres:12.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1882320
      - POSTGRES_DB=MSmileDb
    volumes:
      - /home/v0id/msmile-files/db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
      
  backend:
    environment:
      - ConnectionStrings__MSmileDb=HOST=pg_db;DB=MSmileDb;UID=postgres;PWD=1882320;PORT=5432;
      - LogSettings__Path=/var/lib/msmile/logs/Log-{Date}.log
    build: 
      context: .
      args:
        logpath: /var/lib/msmile/logs/
    ports:
      - "8000:80"
    volumes:
      - /home/v0id/msmile-files/logs:/var/lib/msmile/logs/
    depends_on:
      - pg_db

  ng_proxy:
    image: arm64v8/nginx:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=8001
    volumes:
      - ./ci/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
