version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres:12.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1882320
      - POSTGRES_DB=MSmileDb
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
